# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
