# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_remediation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
