# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
